apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-icqhzgue
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-icqhzgue:c36acc91fb31d61df55695b3a98fcdea89130d27@sha256:b421d05fed0d110849977e8001e6f9f736cb891d39508e5054cd57e0fbe2c2aa
          name: container-image
